# About: File to be used to build Miniconda packages.
# Author: Ivan Vnucec
# License: Do whatever you want with it. I don't care.

# "name: env" variable is used in Dockerfile to run Conda environment. Be carefull when changing name.
name: env
channels:
  - conda-forge
  - defaults
dependencies:
  - gcovr         # Code coverage
  - ninja         # Ninja build system
  - python=3.8    # Python
  - pip           # Pip
  - pip:          # with Pip install:
    - meson       # Meson build system