name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache register
        id: cache-docker-image
        uses: actions/cache@v2
        with:
          path: ./tmp
          key: |
            ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
            ${{ runner.os }}-buildx-${{ hashFiles('**/environment.yml') }}

      - name: Build Docker image if not cached
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: ./scripts/docker_build_image.sh

      - name: Save Docker image if not cached
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: ./scripts/docker_save_image.sh

      - name: Run Clang format check
        run: ./scripts/clang_format_check.sh

      - name: Load cached Docker image
        run: ./scripts/docker_load_image.sh

      - name: Run Docker container
        run: ./scripts/docker_run_container.sh

      - name: Run cppcheck
        run: |
          sudo apt-get install -y cppcheck
          ./scripts/cppcheck_check.sh

      - name: Upload GCC Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coveragereport
          path: ./builddir/meson-logs/coveragereport/
        
      - name: Upload code coverage reports to codecov.io page
        run: bash <(curl -s https://codecov.io/bash) 

      - name: Generate Doxygen documentation
        run: |
          sudo apt-get install doxygen -y
          ./scripts/doxygen_generate.sh
        
      - name: Deploy Doxygen documentation to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/Doxygen/html
